steal.packs('0','1', function(){
steal('//phui/keycode/keycode.js'
,'//phui/selectable/selectable.js'
,'//phui/scrollbar_width/scrollbar_width.js'
,'//phui/combobox/controllers/dropdown_controller.js'
,'//phui/combobox/combobox.js');
steal.end();
/* phui/keycode/keycode.js */
steal.plugins("jquery").then(function(){$.keycode=function(a){var b=$.makeArray(arguments);a=b.shift();for(var e=$.keyname(a),c=0;c<b.length;c++)if(b[c]===e)return true;return false};$.keycode.isNavigation=function(){};$.keycode.keycodes={backspace:"8",tab:"9",enter:"13",shift:"16",ctrl:"17",alt:"18",space:"32","pause/break":"19",pause:"19","break":"19","caps lock":"20",escape:"27","page up":"33","page down":"34",end:"35",home:"36",left:"37",up:"38",right:"39",down:"40",insert:"45","delete":"46",
"0":"48","1":"49","2":"50","3":"51","4":"52","5":"53","6":"54","7":"55","8":"56","9":"57",a:"65",b:"66",c:"67",d:"68",e:"69",f:"70",g:"71",h:"72",i:"73",j:"74",k:"75",l:"76",m:"77",n:"78",o:"79",p:"80",q:"81",r:"82",s:"83",t:"84",u:"85",v:"86",w:"87",x:"88",y:"89",z:"90","left window key":"91","right window key":"92","select key":"93","0":"96","1":"97","2":"98","3":"99","4":"100","5":"101","6":"102","7":"103","8":"104","9":"105","*":"106","+":"107","-":"109",".":"110","/":"111",f1:"112",f2:"113",
f3:"114",f4:"115",f5:"116",f6:"117",f7:"118",f8:"119",f9:"120",f10:"121",f11:"122",f12:"123","num lock":"144","scroll lock":"145",";":"186","=":"187",",":"188","-":"189",".":"190","/":"191","`":"192","[":"219","\\":"220","]":"221","'":"222"};$.keycode.reverseKeycodes={};for(var d in $.keycode.keycodes)$.keycode.reverseKeycodes[$.keycode.keycodes[d]]=d;$.keyname=function(a){if(a.type=="keypress"&&$.browser.msie)return a.keyCode?String.fromCharCode(a.keyCode):String.fromCharCode(a.which);if(!a.keyCode&&
a.which)return String.fromCharCode(a.which);return $.keycode.reverseKeycodes[a.keyCode+""]}});
;
steal.end();
/* phui/selectable/selectable.js */
steal.plugins("jquery/controller","phui/keycode").then(function(){$.Controller.extend("Phui.Selectable",{defaults:{selectableClassName:"selectable",selectedClassName:"selected",activatedClassName:"activated"}},{init:function(){this.selectableEls=this.find("."+this.options.selectableClassName+"[tabindex]")},".{selectableClassName} mouseenter":function(a){a.trigger("select")},".{selectableClassName} click":function(a){a.trigger("activate")},".{selectableClassName} focusin":function(a){a.addClass(this.options.selectedClassName)},
".{selectableClassName} activate":function(a,b){if(!b.originalEvent){b=this.element.find("."+this.options.activatedClassName);b.length&&b.trigger("deactivate");a.addClass(this.options.activatedClassName)}},".{selectableClassName} deactivate":function(a,b){b.originalEvent||a.removeClass(this.options.activatedClassName)},".{selectableClassName} select":function(a){var b=this.element.find("."+this.options.selectedClassName);b.length&&b.trigger("deselect");$.browser.msie&&a.trigger("focusin");a.focus()},
".{selectableClassName} deselect":function(a){a.removeClass(this.options.selectedClassName)},".{selectableClassName} keydown":function(a,b){var c=$.keyname(b);c=="down"&&this.focusNext(a);c=="up"&&this.focusPrev(a);c=="enter"&&a.trigger("activate");$.browser.mozilla||b.preventDefault()},focusNext:function(a){var b=this.selectableEls.filter(":visible"),c=b.eq(0),e=b.eq(-1);if(a[0]==e[0])return c.trigger("select");var d;for(c=0;c<b.length;c++)if(a[0]==b[c]){d=b[c+1];break}$(d).trigger("select")},focusPrev:function(a){var b=
this.selectableEls.filter(":visible"),c=b.eq(0),e=b.eq(-1);if(a[0]==c[0])return e.trigger("select");var d;for(c=0;c<b.length;c++)if(a[0]==b[c]){d=b[c-1];break}$(d).trigger("select")},getFirst:function(){return this.selectableEls.filter(":visible").get(0)},getLast:function(){return this.selectableEls.filter(":visible").get(-1)}})});
;
steal.end();
/* phui/scrollbar_width/scrollbar_width.js */
steal.plugins("jquery").then(function(a){var c=a('<div id="out"><div style="height:200px;"></div></div>').css({position:"absolute",top:"0px",left:"0px",visibility:"hidden",width:"100px",height:"100px",overflow:"hidden"}).appendTo(document.body);a=a(c[0].childNodes[0]);var d=a[0].offsetWidth,b;c.css("overflow","scroll");b=a[0].offsetWidth;if(b==d){a.css("width","100%");b=a[0].offsetWidth}c.remove();(window.Phui||(window.Phui={})).scrollbarWidth=d-b});
;
steal.end();
/* phui/combobox/controllers/dropdown_controller.js */
steal.then(function(){$.Controller.extend("Phui.Combobox.DropdownController",{},{init:function(a,b,c){this.combobox=b;this.options=c;this.hasFocus=false;this.isFirstPass=this.canOpen=true;(a=b.attr("id"))&&this.element.attr("id",a+"_dropdown")},style:function(){this.element.css("width",this.combobox.width());this.options.maxHeight&&this.element.css({height:this.options.maxHeight,overflow:"auto"});if(this.isFirstPass){var a=this;this.find(".item").each(function(b,c){c=$(c);b=this.getModel(c);c.removeClass(a.options.activatedClassName);
b.attr("activated")&&c.addClass(a.options.activatedClassName)})}this.fixOverflowBugInIE7()},fixOverflowBugInIE7:function(){$.browser.msie&&navigator.appVersion.indexOf("MSIE 7.")!=-1&&this.find("ul.phui_selectable").width(this.element[0].clientWidth)},draw:function(a){if(this.isFirstPass){var b;b=a.length?this._makeEl(a.slice(0),0):"<li>No items in the combobox</li>";if(b.indexOf("<li")===0)b="<ul>"+b+"</ul>";this.element.trigger("move",this.combobox);this.element.html(b);this.element.children("ul").phui_selectable({selectedClassName:"selected",
activatedClassName:"activated"})}b={};for(var c=0;c<a.length;c++){var d=a[c];b[d.identity?d.identity():"dropdown_"+d.id]=d}a=this.find(".item");for(c=0;c<a.length;c++){d=$(a[c]);d.show();var e=d[0].className.match(/(dropdown_\d*)/)[0];e&&!b[e]&&d.hide()}this.modelHash=b;this.isFirstPass=false;this.style()},getModel:function(a){return this.modelHash[a[0].className.match(/(dropdown_\d*)/)[0]]},_makeHtmlForAutocompleteData:function(a){for(var b=[],c=0;c<a.length;c++)b.push("<li>"+this.drawItemHtml(a[c],
true)+"</li>");return b.join(" ")},_makeEl:function(a){if(!a.length)return[];for(var b=0,c=[],d=0;d<a.length;d++){var e=e=a[d];e.level>b&&c.push("<ul>");c.push("<li>",this.drawItemHtml(e),"</li>");e.level<b&&c.push("</ul>");b=e.level}return c.join("")},drawItemHtml:function(a,b){return["<span tabindex='0' class='item ",a.identity?a.identity():"dropdown_"+a.id," selectable ",a.enabled?"":this.options.disabledClassName,"' >",b?"":"<span style='float:left;margin-left:",a.level*20,"px'>&nbsp;</span>",
this.options.render.itemTemplate(a),"</span>"].join("")},keyup:function(a,b){$.keyname(b)=="escape"&&this.hide()},".selectable activate":function(a){if(a.hasClass(this.options.disabledClassName))a.removeClass(this.options.activatedClassName);else{var b=this.getModel(a);if(b){this.combobox.controller().val(b.value,a.html());this.element.hide();this.hasFocus=false}}},mouseenter:function(){this.hasFocus=true},"li mouseleave":function(a,b){b.stopPropagation()},mouseleave:function(){this.canOpen=this.hasFocus=
false;this.combobox.find("input[type=text]").focus();this.canOpen=true},windowresize:function(){this.style()},adjustHeightToFitWindow:function(){var a=this.options.maxHeight||0,b=this.element.height(),c=$(window).height()-4*$("body").offset().top;if(a&&c>a)c=a;c&&b>c&&this.element.css({height:0,"overflow-y":"auto"})},getElementFor:function(a){return this.find("."+a.identity?a.identity():"dropdown_"+a.id)},enable:function(a){this.getElementFor(a).removeClass(this.options.disabledClassName)},disable:function(a){this.getElementFor(a).addClass(this.options.disabledClassName)},
hide:function(){this.combobox.controller().resetWatermark();this.element.slideUp("fast");this.hasFocus=false},show:function(){this.combobox.controller().clearWatermark();this.element.css("opacity",0).show().scrollTop(0).trigger("move",this.combobox).hide().css("opacity",1).slideDown("fast",this.callback("shown"))},shown:function(){var a=this;setTimeout(function(){a.style()},1);this.combobox.trigger("open")}})});
;
steal.end();
/* phui/combobox/combobox.js */
steal.plugins("jquery/controller","phui/positionable","phui/selectable","phui/scrollbar_width").controllers("dropdown").then(function(){$.Controller.extend("Phui.Combobox",{defaults:{render:{itemTemplate:function(a){return"<span class='text'>"+a.text+"</span>"}},maxHeight:null,filterEnabled:true,displayHTML:false,selectedClassName:"selected",activatedClassName:"activated",disabledClassName:"disabled",width:null,emptyItemsText:"No items in the combobox",watermarkText:"Click for options"}},{setup:function(a,
b){a=$(a);var c=a.attr("name");c=$("<div><div class='toggle'>&nbsp;</div><div class='viewbox' tabindex='0' style='display:none'/><div class='container'></div><input type='hidden' name='"+c+"'/></div>");var d=c.find(".container");this.oldElement=a.replaceWith(c).removeAttr("name");c.attr("id",this.oldElement.attr("id"));this.oldElement.removeAttr("id");d.append(this.oldElement);this._super(c,b);if(this.options.displayHTML){this.oldElement.hide();this.find(".viewbox").show()}},init:function(){this.options.width&&
this.element.width(this.options.width);this.currentItem={value:null};this.loadData(this.options.items);this.resetWatermark();this.valueSet=true},resetWatermark:function(){this.val()||this.find("input[type='text']").val(this.options.watermarkText)},clearWatermark:function(){var a=this.find("input[type='text']");a.val()==this.options.watermarkText&&a.val("")},dropdown:function(){if(!this._dropdown){this._dropdown=$("<div/>").phui_combobox_dropdown(this.element,this.options).hide();document.body.appendChild(this._dropdown[0]);
this._dropdown.phui_positionable({my:"left top",at:"left bottom",collision:"none none"}).trigger("move",this.element);this._dropdown.controller().style();this.options.items&&this.dropdown().controller().draw(this.modelList)}return this._dropdown},loadData:function(a){if(a)(a=this.makeModelList(a))&&this.val(a.value)},makeModelList:function(a){if(!a||a.length==0)return this.modelList=[];a=this.flattenEls(a.slice(0),0);for(var b,c=[],d,e=0;e<a.length;e++){d=a[e];d=$.extend({id:e+1,enabled:true,children:[],
level:0},typeof d=="string"?{text:d}:d);if(d.selected)b=d;c.push(d)}this.modelList=c;return b},flattenEls:function(a,b,c){c=c||[];b=b||0;if(a&&a.length){var d=a.shift(),e=d.children;d.level=b;c.push(d);this.flattenEls(e,b+1,c);this.flattenEls(a,b,c);return c}},".viewbox click":function(a){this._toggleComboboxView(a)},".viewbox focusin":function(a){this._toggleComboboxView(a)},_toggleComboboxView:function(a){a.hide();a=this.find("input[type='text']");a.show();a[0].focus();a[0].select()},"input keyup":function(a,
b){b=$.keyname(b);if(b=="escape"){this.dropdown().controller().hide();return false}if(b=="down"){this.dropdown().controller().hasFocus=true;a=this.dropdown().children("ul").controller().getFirst();$(a).trigger("select")}else if(b=="up"){this.dropdown().controller().hasFocus=true;a=this.dropdown().children("ul").controller().getLast();$(a).trigger("select")}else this.autocomplete(a.val())},autocomplete:function(a){if(this.options.filterEnabled)if(this.modelList&&this.modelList[0]&&this.modelList[0].text){var b=
true,c=$.grep(this.modelList,function(d){return d.text.indexOf(a)>-1});if(!a||$.trim(a)=="")b=false;this.dropdown().controller().draw(c,b);this.dropdown().is(":visible")||this.dropdown().controller().show()}},"input focusin":function(a){this.focusInputAndShowDropdown(a)},"input click":function(a){this.focusInputAndShowDropdown(a)},focusInputAndShowDropdown:function(a){if(a[0].tagName.toUpperCase()=="INPUT"&&a.is(":visible")){a[0].focus();setTimeout(function(){a[0].select()});if(!this.dropdown().is(":visible")&&
this.dropdown().controller().canOpen){this.dropdown().controller().show();a.trigger("show:dropdown",this)}}},focusin:function(){this.closeDropdownOnBlurTimeout&&clearTimeout(this.closeDropdownOnBlurTimeout)},focusout:function(){if(!this.dropdown().is(":hidden")){var a=this;this.closeDropdownOnBlurTimeout=setTimeout(function(){if(a.dropdown().controller().hasFocus)a.element.trigger("focusin");else{a.currentItem.item&&a._setViewboxHtmlAndShow(a.options.render.itemTemplate(a.currentItem.item));a.dropdown().controller().hide()}},
250)}},mouseleave:function(){this.dropdown().is(":visible")&&this.find("input[type='text']").focus()},modelListMatches:function(a,b){return $.grep(this.modelList,function(c){return c[a]==b})},textVal:function(){return this.find("input[type=text]").val()},val:function(a){if(a===undefined)return this.currentItem.value;if(a=this.modelListMatches("value",a)[0]){var b=this.options.render.itemTemplate(a);this.currentItem.item&&(this.currentItem.item.activated=false);this.currentItem={value:a.value,item:a,
html:b};a.activated=true;this.oldElement[0].value=a.text;this.options.displayHTML&&this._setViewboxHtmlAndShow(b);this.find("input[type=hidden]")[0].value=this.currentItem.value;this._dropdown&&this.dropdown().controller().draw(this.modelList);this.valueSet&&this.element.trigger("change",this.currentItem.value)}},_setViewboxHtmlAndShow:function(a){if(this.options.displayHTML){this.find("input[type=text]").hide();this.find(".viewbox").show().html(a||"")}},select:function(a){(a=this.modelListMatches("value",
a)[0])&&this.dropdown().controller().select(a)},clearSelection:function(){if(this.currentItem.item){this.find("input[type='text']").val("");this.dropdown().controller().clearSelection(this.currentItem.item);this.currentItem={value:null,item:null,html:null}}},getItems:function(){return this.modelList},populateItems:function(a){this.find("input[type='text']").trigger("show:dropdown",[this,a])},query:function(a){for(var b=$.grep(this.modelList,function(e){return e.text.indexOf(a)>-1}),c=[],d=0;d<b.length;d++)c.push(b[d].value);
return c},enable:function(a){if(a=this.modelListMatches("value",a)[0]){a.enabled=true;this.dropdown().controller().enable(a)}},disable:function(a){if(a=this.modelListMatches("value",a)[0]){a.enabled=false;a.activated=false;this.dropdown().controller().disable(a)}},".toggle click":function(){this.dropdown().is(":visible")?this.dropdown().controller().hide():this.focusInputAndShowDropdown(this.find("input[type=text]"));var a=this.find(".viewbox");a.is(":visible")&&this._toggleComboboxView(a)},".toggle dblclick":function(){if($.browser.msie){this.dropdown().is(":visible")?
this.dropdown().controller().hide():this.dropdown().controller().show();this.focusInputAndShowDropdown(this.find("input[type=text]"))}},destroy:function(){this.dropdown().remove();this.oldElementName=this.modelList=this._dropdown=null;var a=this.element;this._super();a.replaceWith(this.oldElement);this.oldElement=null}})});

});